### ISSUE TITLE
Allow user to expand Read more on Business card

### ISSUE THREAD

**Issue by anhyesun** [CPSC436/ThinkSmall#56]
**User story**
As a user, I want to be able to see the full description of a business so that I can check what kind of businesses by reading the description.

**Acceptance criteria**
- Expand a business card to show the business's full description when a user clicked `Read More` button on a business card 
- Note: `read more` should be shown when the business description is longer than the limit of card description.

**Comment by giteshk11** [comment]
Hi @anhyesun, I would like to work on this :)

**Comment by yehee** [comment]
I wasn't aware of this issue ticket, but I just realized that I addressed this issue on #69. Do you want to make sure that the functionality meets the criteria?
