### ISSUE TITLE
Implement Account page for a user

### ISSUE THREAD

**Issue by anhyesun** [CPSC436/ThinkSmall#57]
**User story**
As a user, I want to be able to edit/delete requests as well as a business list on the account page so that I can easily update my store information and help. 

**Acceptance criteria**
- Create `account` page that has user information (dummy data for the user is fine) 
- Ensure that updated information is reflected in the `account` page 
#34 is related to this issue 

![image](https://user-images.githubusercontent.com/39198761/85487095-c2fca500-b580-11ea-9662-cd3ef1ed6529.png)

**Comment by yehee** [comment]
This would require a lot of dev time, might as well split up into sub-tasks e.g. lo-fi mock up, redux layer, API, connecting to DB?

**Comment by anhyesun** [comment]
Yes, that would be a good idea. I'll update issues tomorrow or Wednesday, but if anyone wants to make a new issue, feel free to do so :)

**Comment by yehee** [comment]
Closing this issue as this has been split into #66 `frontend`, #67 `backend`.
